# Generated by Django 4.2 on 2025-01-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addbookingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=200)),
                ('project_id', models.CharField(max_length=500)),
                ('site_no', models.CharField(max_length=500)),
                ('booking_date', models.CharField(max_length=500)),
                ('cost', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='addbuilderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builder_name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=500)),
                ('start_date', models.CharField(max_length=500)),
                ('no_of_project', models.CharField(max_length=500)),
                ('web_site', models.CharField(max_length=500)),
                ('email_id', models.CharField(max_length=500)),
                ('contact_no', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='addcustomerdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('contact_no', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='addprojectdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('start_date', models.CharField(max_length=100)),
                ('plan_image', models.FileField(upload_to='documents/')),
                ('end_date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='addsitedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=200)),
                ('site_no', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('site_type', models.CharField(max_length=500)),
                ('estimate_cost', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='newreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('contact_no', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
    ]
